import { addIcon } from "@iconify/vue/dist/offline";

import Cloud from "@iconify-icons/material-symbols/cloud";
import Download from "@iconify-icons/material-symbols/download-2";
import FileCopySharp from "@iconify-icons/material-symbols/file-copy-sharp";
import InfoSharp from "@iconify-icons/material-symbols/info-sharp";
import refreshRounded from "@iconify-icons/material-symbols/refresh-rounded";
import RocketLaunchRounded from "@iconify-icons/material-symbols/rocket-launch-rounded";
import Settings from "@iconify-icons/material-symbols/settings";

import Add from "@iconify-icons/material-symbols/add";
import attachMoneyRounded from "@iconify-icons/material-symbols/attach-money-rounded";
import BringYourOwnIpRounded from "@iconify-icons/material-symbols/bring-your-own-ip-rounded";
import CancelPresentation from "@iconify-icons/material-symbols/cancel-presentation";
import chargerRounded from "@iconify-icons/material-symbols/charger-rounded";
import CheckBox from "@iconify-icons/material-symbols/check-box";
import CheckCircleRounded from "@iconify-icons/material-symbols/check-circle-rounded";
import ContentCopy from "@iconify-icons/material-symbols/content-copy";
import ContentPasteGo from "@iconify-icons/material-symbols/content-paste-go";
import DeleteRounded from "@iconify-icons/material-symbols/delete-rounded";
import description from "@iconify-icons/material-symbols/description";
import deviceReset from "@iconify-icons/material-symbols/device-reset";
import downloadRounded from "@iconify-icons/material-symbols/download-rounded";
import Edit from "@iconify-icons/material-symbols/edit";
import Error from "@iconify-icons/material-symbols/error";
import ExportNotesOutline from "@iconify-icons/material-symbols/export-notes-outline";
import fileOpenRounded from "@iconify-icons/material-symbols/file-open-rounded";
import fileSaveRounded from "@iconify-icons/material-symbols/file-save-rounded";
import folderRounded from "@iconify-icons/material-symbols/folder-rounded";
import GestureSelect from "@iconify-icons/material-symbols/gesture-select";
import Info from "@iconify-icons/material-symbols/info";
import link from "@iconify-icons/material-symbols/link";
import moreHoriz from "@iconify-icons/material-symbols/more-horiz";
import MoreVert from "@iconify-icons/material-symbols/more-vert";
import networkNode from "@iconify-icons/material-symbols/network-node";
import QuestionMark from "@iconify-icons/material-symbols/question-mark";
import SaveRounded from "@iconify-icons/material-symbols/save-rounded";
import switchAccessOutlineRounded from "@iconify-icons/material-symbols/switch-access-outline-rounded";
import switchAccessRounded from "@iconify-icons/material-symbols/switch-access-rounded";
import toggleOff from "@iconify-icons/material-symbols/toggle-off";
import toggleOn from "@iconify-icons/material-symbols/toggle-on";
import unarchive from "@iconify-icons/material-symbols/unarchive";
import uploadRounded from "@iconify-icons/material-symbols/upload-rounded";
import volunteerActivismSharp from "@iconify-icons/material-symbols/volunteer-activism-sharp";

addIcon("cloud", Cloud);
addIcon("rocket-launch-rounded", RocketLaunchRounded);
addIcon("download", Download);
addIcon("settings", Settings);
addIcon("file-copy-sharp", FileCopySharp);
addIcon("info-sharp", InfoSharp);
addIcon("refresh-rounded", refreshRounded);
addIcon("more-vert", MoreVert);
addIcon("add", Add);
addIcon("bring-your-own-ip-rounded", BringYourOwnIpRounded);
addIcon("charger-rounded", chargerRounded);
addIcon("delete-rounded", DeleteRounded);
addIcon("cancel-presentation", CancelPresentation);
addIcon("gesture-select", GestureSelect);
addIcon("save-rounded", SaveRounded);
addIcon("info", Info);
addIcon("question-mark", QuestionMark);
addIcon("check-circle-rounded", CheckCircleRounded);
addIcon("error", Error);
addIcon("content-copy", ContentCopy);
addIcon("content-paste-go", ContentPasteGo);
addIcon("edit", Edit);
addIcon("check-box", CheckBox);
addIcon("export", ExportNotesOutline);
addIcon("uploadRounded", uploadRounded);
addIcon("downloadRounded", downloadRounded);
addIcon("deviceReset", deviceReset);
addIcon("switchAccessOutlineRounded", switchAccessOutlineRounded);
addIcon("switchAccessRounded", switchAccessRounded);
addIcon("file-open-rounded", fileOpenRounded);
addIcon("attach-money-rounded", attachMoneyRounded);
addIcon("volunteer-activism-sharp", volunteerActivismSharp);
addIcon("description", description);
addIcon("folder-rounded", folderRounded);
addIcon("link", link);
addIcon("unarchive", unarchive);
addIcon("file-save-rounded", fileSaveRounded);
addIcon("toggle-on", toggleOn);
addIcon("toggle-off", toggleOff);
addIcon("more-horiz", moreHoriz);
addIcon("network-node", networkNode);
