[package]
name = "frpc-desktop"
version = "1.2.8"
description = "FRP Desktop Client"
authors = ["luckjiawei"]
edition = "2021"

[lib]
name = "frpc_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.7.0", features = [] }

[dependencies]
tauri = { version = "2.12.0", features = ["tray-icon", "image-png"] }
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"
tauri-plugin-autostart = "2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
rusqlite = { version = "0.31", features = ["bundled"] }
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["json", "stream"] }
sysinfo = "0.33"
sha2 = "0.10"
flate2 = "1.0"
tar = "0.4"
zip = { version = "2.2", default-features = false, features = ["deflate"] }
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1", features = ["v4", "serde"] }
log = "0.4"
dirs = "6.0"
anyhow = "1.0"
libc = "0.2"
md5 = "0.7"
open = "5.3"
rfd = "0.15"
futures-util = "0.3"
